spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit

springdoc:
  swagger-ui:
    urls:
      - name: User API
        url: /api-docs/user-api.yaml
